AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bia-serverless

  Sample SAM Template for bia-serverless
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  BiaAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bia/
      Handler: lambda.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyPath:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DB_HOST: "database"
          DB_PORT: 5432
          DB_USER: "postgres"
          DB_PWD: "postgres"

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  BiaApiUrl:
    Description: "API Gateway endpoint URL for BIA application"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  BiaAppFunction:
    Description: "BIA Lambda Function ARN"
    Value: !GetAtt BiaAppFunction.Arn
