AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bia-serverless

  Sample SAM Template for bia-serverless
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  TarefasFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bia/
      Handler: lambda.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        Ping:
          Type: Api 
          Properties:
            Path: /api/ping
            Method: get
        GetTarefas:
          Type: Api 
          Properties:
            Path: /api/tarefas
            Method: get
        PostTarefas:
          Type: Api
          Properties:
            Path: /api/tarefas
            Method: post    
        GetTarefa:
          Type: Api 
          Properties:
            Path: /api/tarefas/{uuid}
            Method: get
        UpdatePriorit:
          Type: Api 
          Properties:
            Path: /api/tarefas/update_priority/{uuid}
            Method: put
        DeleteTarefa:
          Type: Api 
          Properties:
            Path: /api/tarefas/{uuid}
            Method: delete
        Ping:
          Type: Api
          Properties:
            Path: /api/ping
            Method: get              
      Environment:
        Variables:
          DB_USER: postgres
          DB_PWD: 4HVCbGO1iaxHBU0fJzLJ
          DB_HOST: db-lambda.cgrawk6w02jf.us-east-1.rds.amazonaws.com
          DB_PORT: 5432
    Metadata:
      BuildMethod: makefile


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Tarefas function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/api/tarefas/"
  HelloWorldFunction:
    Description: "Tarefas Lambda Function ARN"
    Value: !GetAtt TarefasFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TarefasFunctionRole.Arn
